```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: healthcare-app
  namespace: {{ .Values.global.namespace }}
  labels:
    app: healthcare-app
spec:
  selector:
    matchLabels:
      app: healthcare-backend
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
  namespaceSelector:
    matchNames:
      - {{ .Values.global.namespace }}
```
