```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: healthcare-access-binding
  namespace: {{ .Values.global.namespace }}
subjects:
- kind: Group
  name: developers
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: healthcare-access
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: healthcare-cicd-binding
  namespace: {{ .Values.global.namespace }}
subjects:
- kind: ServiceAccount
  name: cicd-sa
  namespace: {{ .Values.global.namespace }}
roleRef:
  kind: Role
  name: healthcare-cicd
  apiGroup: rbac.authorization.k8s.io
```
