```yaml
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/patientdb
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
logging:
  level:
    root: INFO
    com.healthcare: DEBUG
server:
  port: 8080
```
