```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-backend
  namespace: {{ .Values.global.namespace }}
  labels:
    app: healthcare-backend
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: healthcare-backend
  template:
    metadata:
      labels:
        app: healthcare-backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      imagePullSecrets: {{ .Values.global.imagePullSecrets | toYaml | nindent 8 }}
      containers:
      - name: backend
        image: {{ .Values.image }}
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://{{ .Values.dbHost }}:5432/{{ .Values.dbName }}
        - name: SPRING_DATASOURCE_USERNAME
          value: {{ .Values.dbUsername }}
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.name }}
              key: db_password
        - name: AWS_REGION
          value: {{ .Values.global.awsRegion }}
        resources: {{ .Values.resources | toYaml | nindent 12 }}
        livenessProbe: {{ .Values.livenessProbe | toYaml | nindent 12 }}
        readinessProbe: {{ .Values.readinessProbe | toYaml | nindent 12 }}
        volumeMounts:
        - name: config
          mountPath: /app/config/application.yml
          subPath: application.yml
        - name: logs
          mountPath: /var/log
      volumes:
      - name: config
        configMap:
          name: {{ .Values.configMap.name }}
      - name: logs
        emptyDir: {}
```
