```yaml
apiVersion: v1
kind: Service
metadata:
  name: healthcare-backend
  namespace: {{ .Values.global.namespace }}
  labels:
    app: healthcare-backend
spec:
  selector:
    app: healthcare-backend
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  type: ClusterIP
```
