```yaml
postgresqlUsername: admin
postgresqlDatabase: patientdb
postgresqlPasswordSecret: healthcare-app-secrets
configMap:
  enabled: true
  name: healthcare-postgres-config
secret:
  enabled: true
  name: healthcare-app-secrets
resources:
  requests:
    cpu: "500m",
    memory: "512Mi"
  limits:
    cpu: "1000m",
    memory: "1024Mi"
storage:
  size: 20Gi
  storageClass: gp2
pv:
  enabled: true
  name: healthcare-postgres-pv
pvc:
  enabled: true
  name: healthcare-postgres-pvc
networkPolicy:
  enabled: true
```

#### Ingress Controller
<xaiArtifact artifact_id="23d06d05-dac3-461e-b45f-0573ebd2a872" artifact_version_id="99790922-8c41-4bb9-a168-e66f389ea1bb" title="helm/healthcare-app/templates/ingress/ingress-controller.yaml" contentType="text/yaml">
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress-controller
  namespace: {{ .Values.global.namespace }}
  labels:
    app: nginx-ingress-controller
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-ingress-controller
  template:
    metadata:
      labels:
        app: nginx-ingress-controller
    spec:
      serviceAccountName: nginx-controller-sa
      containers:
      - name: controller
        image: k8s.gcr.io/ingress-nginx/controller:v1.0.0
        args:
        - /nginx-ingress-controller
        - --configmap=$(POD_NAMESPACE)/nginx-config
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10254
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 10254
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-controller
  namespace: {{ .Values.global.namespace }}
  labels:
    app: nginx-ingress-controller
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: nginx-ingress-controller
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{ .Values.global.namespace }}
  labels:
    app: nginx-ingress-controller
data:
  enable-underscores-in-headers: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-controller-sa
  namespace: {{ .Values.global.namespace }}
```
