```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: {{ .Values.global.namespace }}
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /fluentd/log/fluentd.pos
      read_from_head true
      tag kubernetes.*
      <label>@kubernetes>
        <filter **>
          @type kubernetes_metadata
        </filter>
        <match **>
          @type cloudwatch_logs
          log_group_name {{ .Values.global.logging.fluentd.cloudwatch.logGroup }}
          log_stream_name fluentd-${HOSTNAME}
          region {{ .Values.global.awsRegion }}
          auto_create_stream true
          <buffer>
            flush_interval 5s
            chunk_limit_size 1m
            queue_limit 128
            retry_forever true
          end>
        </match>
      </label>
    end>
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      serviceAccountName: fluentd
      containers:
      - name: fluentd
        image: fluentd:v1.12.0
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluentd-config
          mountPath: /fluentd/etc
        - name: fluentd-pos
          mountPath: /fluentd/log
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluentd-config
        configMap:
          name: fluentd-config
      - name: fluentd-pos
        emptyDir: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
  namespace: {{ .Values.global.namespace }}
```
