```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: healthcare-app-secrets
  namespace: {{ .Values.global.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: healthcare-app-secrets
    creationPolicy: Owner
  data:
    - secretKey: db_password
      remoteRef:
        key: secret/healthcare/data/db
        property: db_password
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    name: vault
      server: "{{ .Values.global.vaultAddr }}"
      path: secret
      version: v2
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: {{ .Values.global.namespace }}
type: Secret
data:
  name: {{ .Values.global.vault_token | b64enc }}
```
