```yaml
apiVersion: v1
kind: Service
metadata:
  name: healthcare-frontend
  namespace: {{ .Values.global.namespace }}
  labels:
    app: healthcare-frontend
spec:
  selector:
    app: healthcare-frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  type: ClusterIP
```
